### ISSUE TITLE
Issues for datasets

### ISSUE THREAD

**Issue by YanJiangJerry** [ZhuYun97/GraphCLIP#1]
Could you please upload the dataset file for each dataset you use? looks like all data files are missing.

**Comment by ZhuYun97** [comment]
Thanks for your interest in our work. We are in the process of updating our codes and will gradually release our pretrained checkpoint along with all the datasets we utilized.

To facilitate an easy start, we have provided the following datasets: PubMed as the source and CiteSeer as the target. You can run our code with the commands below:

```python
# Pretraining on PubMed
CUDA_VISIBLE_DEVICES=0,1 python train.py --source_data pubmed

# Evaluation on CiteSeer
CUDA_VISIBLE_DEVICES=0 python eval.py --target_data citeseer
```

If you encounter any issues or have questions, please feel free to reach out to us.

**Comment by YanJiangJerry** [comment]
Thanks for your prompt response. I'm just confused with the data loading for these two sample dataset. Looks like the load pubmed function need a .pub file instead of the .pt original pubmed dataset, could you update the data loader function or provide the .pub files?

The error looks like:
` with open(path + 'Pubmed-Diabetes.NODE.paper.tab', 'r') as node_file:
FileNotFoundError: [Errno 2] No such file or directory: '../datasets/PubMed_orig/data/Pubmed-Diabetes.NODE.paper.tab'`

**Comment by ZhuYun97** [comment]
This error occurs due to the incorrect path. We have updated the repository. Kindly pull the latest changes or redownload the repository.
