### ISSUE TITLE
'list' object has no attribute 'x' problem when pre-training the code

### ISSUE THREAD

**Issue by LuShuaiqi-Geo** [ZhuYun97/GraphCLIP#2]
Hello, when I was pre-training the code, I entered：

`CUDA_VISIBLE_DEVICES=0,1 python train.py --source_data pubmed --batch_size 1024 --epochs 30`

There is an error：

> graph_embs, center_embs = self.graph_model(batch.x, batch.pe, batch.edge_index, batch.batch, batch.root_n_index)
> AttributeError: 'list' object has no attribute 'x'

It seems like batch is a python list, whose element has a atrribute x. In this line, it directly use x of this list as a parameter, but this x does not exist.

I tried to rewrite the relevant function and use the elements of the list as parameters：
```
def encode_graph(self, batch):
    graph_embs = []
    center_embs = []

    for element in batch:
        emb_result = self.graph_model(element.x, element.pe, element.edge_index, element.batch, element.root_n_index)
        graph_embs.append(emb_result[0])
        center_embs.append(emb_result[1])
```
but this led to another error, which was related to the forward function in gt.py. The error message is as follows:

> GraphCLIP-main/models/gt.py", line 61, in forward
    g_x=torch.cat((g_x, c_x), 1) # cat average and center
RuntimeError: Tensors must have same number of dimensions: got 2 and 1

Could you please provide some suggestions to solve this problem?

**Comment by ZhuYun97** [comment]
Hi, thank you for reaching out and bringing this to our attention.

Have you made any modifications to the code? We have successfully run the repository without any changes. Regarding the first error you encountered, we utilize `torch_geometric.nn.DataParallel` to [wrap the graph model](https://github.com/ZhuYun97/GraphCLIP/blob/main/train.py#L65). This approach automatically collates `list` into `batch`, which should prevent the error you mentioned from occurring.

Could you please let us know which version of `torch_geometric` you are using? We are currently using version 2.4.0 or newer. Ensuring compatibility with this version might resolve the issue you're experiencing.

If you continue to face difficulties, please provide more details about the error messages or any changes you've made. We're here to help and want to ensure everything runs smoothly for you.

**Comment by ZhuYun97** [comment]
We have updated the `README.md` to include information about the running environment. Please refer to it for setup instructions.

**Comment by ZhuYun97** [comment]
Could you please provide details about your GPU environment? It appears that there might be an insufficient number of GPUs available. If you do have the required GPUs, please ensure that you follow the environment setup instructions provided in the README.md file.

**Comment by LuShuaiqi-Geo** [comment]
Yes, I'm using a server with 8 RTX3090 cards, and when I run the code, there are two idle GPUs on the server. Then I ran train.py and the above problem occurred

**Comment by LuShuaiqi-Geo** [comment]
> We have updated the `README.md` to include information about the running environment. Please refer to it for setup instructions.

I created a new environment, used the recommended library version, and found that the code could run train.py normally. 
So I think the above problem may still be caused by some conflicts due to different library versions.
Anyway, thank you very much for your help and reply！
