### ISSUE TITLE
Class information required for some datasets

### ISSUE THREAD

**Issue by LuShuaiqi-Geo** [ZhuYun97/GraphCLIP#3]
When I tried to use the provided reddit dataset and arxiv_2023 dataset for testing, I found that in /data/load.py, there was no class information including the above dataset,
```    
elif dataset == 'ogbn-arxiv':
    from data.data_utils.load_arxiv import get_raw_text_arxiv as get_raw_text
    num_classes = 40
    classes=[]
    c_descs=[]

elif dataset == 'ogbn-products':
    from data.data_utils.load_products import get_raw_text_products as get_raw_text
    num_classes = 47
    classes = []
    c_descs = []
elif dataset == 'arxiv_2023':
    from data.data_utils.load_arxiv_2023 import get_raw_text_arxiv_2023 as get_raw_text
    num_classes = 40
    classes = []
    c_descs = []
```
At the same time, because the json file you provided only contains vertex numbers, subgraphs, and summaries. I want to know how you know which class each vertex belongs to. Is there some other file that provides the real label information?

**Comment by LuShuaiqi-Geo** [comment]
Another question is, regarding the dataset, such as the pubmed dataset, can you share how to find the text content of the original text corresponding to the vertex. Since I don't know much about these datasets, most of the datasets like pubmed I found on the web do not come with raw text content. I'm more curious about how you obtained the text content. I would be very grateful if you could answer this question.

**Comment by ZhuYun97** [comment]
Thank you for your interest in our work.

We are continuously updating this repository and plan to upload the raw texts for each dataset shortly. In the meantime, you may find raw texts through other resources such as [TAPE](https://github.com/XiaoxinHe/TAPE), [CS-TAG](https://github.com/sktsherlock/TAG-Benchmark) and [GLEM](https://github.com/AndyJZhao/GLEM/blob/main/src/utils/settings.py#L100).

Please feel free to reach out if you have any further questions or need assistance.

**Comment by LuShuaiqi-Geo** [comment]
Thank you very much for your detailed reply！
